automated tests for debian scripts and great refactoring for bash DRY

diff --git a/debian/debian/ka-lite-raspberry-pi.postrm b/debian/debian/ka-lite-raspberry-pi.postrm
--- a/debian/debian/ka-lite-raspberry-pi.postrm
+++ b/debian/debian/ka-lite-raspberry-pi.postrm
@@ -5,34 +5,38 @@ set -e
 
 # Restore diversion for /etc/nginx/nginx.conf
 # https://wiki.debian.org/Adding%20and%20removing%20diversions
-pkg=ka-lite-raspberry-pi
 diversion_added_version=0.14
-this_version=0.14
+this_version=0.15
 
 losing_diversion=n
 
 if test "$1" = failed-upgrade
 then
-        dpkg --compare-versions "$2" le-nl "$this_version" ||
-        # An upgrade from a newer version failed.
-        # There is no way for us to know enough to take over from here,
-        # so abort the upgrade.
-        exit 1
+    dpkg --compare-versions "$2" le-nl "$this_version" ||
+    # An upgrade from a newer version failed.
+    # There is no way for us to know enough to take over from here,
+    # so abort the upgrade.
+    exit 1
 elif dpkg --compare-versions "$2" lt-nl "$diversion_added_version"
 then
+    diversion_list=`dpkg-divert --list /etc/nginx/nginx.conf`
+    if ! [ "$diversion_list" = "" ]
+    then
         losing_diversion=y
+    fi
 fi
 
 case "$1,$losing_diversion" in
 remove,*|abort-install,*|disappear,*|*,y)
-        # Remove the file to avoid:
-        #    Removing 'diversion of /etc/nginx/nginx.conf to /etc/nginx/nginx.conf-ka-lite-raspberry-pi by ka-lite-raspberry-pi'
-        #    dpkg-divert: error: rename involves overwriting `/etc/nginx/nginx.conf' with
-        #    different file `/etc/nginx/nginx.conf-ka-lite-raspberry-pi', not allowed
-        # rm -f /etc/nginx/nginx.conf
-        dpkg-divert --package "$pkg" --remove --rename /etc/nginx/nginx.conf
-        # dpkg-divert --package "$pkg" --remove /etc/nginx/nginx.conf
-        ;;
+    # Remove the file to avoid:
+    #    Removing 'diversion of /etc/nginx/nginx.conf to /etc/nginx/nginx.conf-ka-lite-raspberry-pi by ka-lite-raspberry-pi'
+    #    dpkg-divert: error: rename involves overwriting `/etc/nginx/nginx.conf' with
+    #    different file `/etc/nginx/nginx.conf-ka-lite-raspberry-pi', not allowed
+    # rm -f /etc/nginx/nginx.conf
+    # removed the --package directive by recommendation of #debian-mentor
+    dpkg-divert --remove --rename /etc/nginx/nginx.conf
+    # dpkg-divert --package "$pkg" --remove /etc/nginx/nginx.conf
+    ;;
 esac
 
 
