If postinst fails, the package configuration is broken. Don't allow this to happen because the service fails to start, this causes lots of headaches for people who just happen to have a silly system.

diff --git a/debian/debian/ka-lite-bundle.postinst b/debian/debian/ka-lite-bundle.postinst
--- a/debian/debian/ka-lite-bundle.postinst
+++ b/debian/debian/ka-lite-bundle.postinst
@@ -57,8 +57,8 @@ case "$1" in
         echo "Adding script to startup"
         update-rc.d ka-lite defaults
 
-        # Start service
-        invoke-rc.d ka-lite start
+        # Start service - nevermind if it fails
+        invoke-rc.d ka-lite start || true
     fi
 
   ;;
